### ISSUE TITLE
[nssdca-delivery] urn:nasa:pds:mars2020_meda

### ISSUE THREAD

**Issue by ghost** [NASA-PDS/operations#154] opened 2021-09-14 15:40 UTC
## Discipline Node Information

**Delivering Node**: PDS_ATM

**NSSDCA Delivery Package**: 
[mars2020_meda_v1.0_20210913.tar.gz](https://github.com/NASA-PDS/pdsen-operations/files/7163253/mars2020_meda_v1.0_20210913.tar.gz)

**Validation report**: 
[medaval.txt](https://github.com/NASA-PDS/pdsen-operations/files/7163259/medaval.txt)

----

## Engineering Node Process

See the internal EN process at https://pds-engineering.jpl.nasa.gov/content/nssdca_interface_process

**Comment by c-suh** [comment] 2021-09-14 20:27
@Astro-Joni, please
- use the [latest version](https://github.com/NASA-PDS/validate/releases/tag/v2.0.7) of the Validate tool
- run the Validate tool with the flag enabled for the appropriate rule, i.e. `-R pds4.bundle`

**Comment by c-suh** [comment] 2021-09-14 20:27
Note: re-submission of #151

**Comment by Astro-Joni** [comment] 2021-09-14 20:54
Catherine Suh ***@***.***> wrote:

>
***@***.***, please
>- use the [latest version](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-PDS%2Fvalidate%2Freleases%2Ftag%2Fv2.0.7&amp;data=04%7C01%7Cjojohnso%40astronomy.nmsu.edu%7Cb94f3390e18e447f66c408d977be1e1a%7Ca3ec87a89fb84158ba8ff11bace1ebaa%7C1%7C0%7C637672480727303767%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=MvvWYzGaUM5%2BfjoQkKRN925Gd6zK1nB7yltMdkpTzWo%3D&amp;reserved=0) of the Validate tool
>- run the Validate tool with the flag enabled for the appropriate rule, i.e. `-R pds4.bundle`

Lyle says he uses the -R pds4.bundle for his validation (I just asked him
a bit ago).  But I'll ask him which version of validate he's using.

Joni

**Comment by c-suh** [comment] 2021-09-14 20:59
@Astro-Joni, is there perhaps a later validation report which was not submitted? The one attached in the description indicates - Validate version 2.0.4 (top of report) and
- no presence of a Rule Type (top of report) nor any referential integrity checks (bottom of report)

**Comment by Astro-Joni** [comment] 2021-09-14 21:04
Catherine Suh ***@***.***> wrote:

>
***@***.***, is there perhaps a later validation report which was not submitted? The one attached in the description indicates - Validate version 2.0.4 (top of report) and
>- no presence of a Rule Type (top of report) nor any referential integrity checks (bottom of report)
>

I'm double-checking with Lyle...maybe in his hurry to get it to me,
he didn't do the rule type.

Joni

**Comment by c-suh** [comment] 2021-10-06 17:00
Hello @Astro-Joni, any update on the validation for set `mars2020_meda` regarding the Validation Tool version and run with the Rule Type, i.e. -R pds4.bundle ?

**Comment by smclaughlin7** [comment] 2021-10-06 17:18
Hi Catherine

Joni Johnson retired last week, although she still expects to occassionally check in with Atmospheres Node.  Tina Gueth ***@***.******@***.***>) is taking over Joni’s PDS4 submission task.

Could you please invite Tina to join the PDS EN Operations site on GitHub so she can post and work on PDS4 submissions, including the outstanding validation concern about the “mars2020_meda” bundle that Joni submitted as GitHub issue #154<https://github.com/NASA-PDS/pdsen-operations/issues/154>?

Thanks!
stef


On 10/6/21, 13:00 , ***@***.******@***.***>> wrote:


Hello @Astro-Joni<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAstro-Joni&data=04%7C01%7Cstephanie.a.mclaughlin%40nasa.gov%7C616f258b5399470323c208d988ead950%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637691364519205293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XbWEKco6chMCaMMCyU2vUXQ6bSWm%2BkD%2BREpD65fegcM%3D&reserved=0>, any update on the validation for set mars2020_meda regarding the Validation Tool version and run with the Rule Type, i.e. -R pds4.bundle ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-PDS%2Fpdsen-operations%2Fissues%2F154%23issuecomment-936692353&data=04%7C01%7Cstephanie.a.mclaughlin%40nasa.gov%7C616f258b5399470323c208d988ead950%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637691364519205293%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=z0UcrnACl8AqOHJaGoElz4vNMF2qcOqujPSQEuV9r%2FU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARALWICYSAV3W72OGMTLPRTUFR6D5ANCNFSM5EAOJ5IA&data=04%7C01%7Cstephanie.a.mclaughlin%40nasa.gov%7C616f258b5399470323c208d988ead950%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637691364519215249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Pvkn5c0%2BUiZxOdA7FvxjsMh%2BQPU%2BmJeBB1Xodt960XI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cstephanie.a.mclaughlin%40nasa.gov%7C616f258b5399470323c208d988ead950%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637691364519215249%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gS33VBRnoCQkLCyh%2BvmOf7sXtbvlUB%2BOWvJzDmkfcZ8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cstephanie.a.mclaughlin%40nasa.gov%7C616f258b5399470323c208d988ead950%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637691364519225205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x6w69r3o8d7zxXPZsfh6gxSZcTdTCFHjGNOhoS8k8bQ%3D&reserved=0>.

**Comment by c-suh** [comment] 2021-10-06 17:47
Hi @smclaughlin7, Tina doesn't have to be a member of NASA-PDS/pdsen-operations in order to submit and work on tickets such as these, but it is helpful to know whom to look for in Joni's stead, so thank you for the information!

@Astro-Joni, happy retirement! I appreciate you checking in on this open ticket and hope it doesn't interfere too much with your newfound freedom.

**Comment by Astro-Joni** [comment] 2022-04-27 17:03
Catherine Suh ***@***.***> wrote:

>
>hello @Astro-Joni and @tinagueth, a quick reminder for this mars2020_meda package:
>- update to the [latest version](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNASA-PDS%2Fvalidate%2Freleases%2Flatest&amp;data=05%7C01%7Cjojohnso%40astronomy.nmsu.edu%7C6dadf4eb1e1b440419c908da286bad23%7Ca3ec87a89fb84158ba8ff11bace1ebaa%7C1%7C0%7C637866740191091135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=3fIjGpY%2BXxxh%2BG%2FWDAL5f9%2F3qfSUX7ZCykqIcRH2f64%3D&amp;reserved=0) of the Validate tool (currently v2.2.0)
>- run the Validate tool with `-R pds4.bundle`
>- resubmit the new validation report and delivery package
>

Hi Catherine,
I am retired and no longer working on this.  Or anything PDS related.
Tina Gueth should be your sole contact.

Joni

**Comment by c-suh** [comment] 2022-04-27 17:46
@tinagueth your recent submissions are good (https://github.com/NASA-PDS/operations/issues/248 and https://github.com/NASA-PDS/operations/issues/249). However, the one for `lab.hydrocarbon_spectra` (https://github.com/NASA-PDS/operations/issues/173) is still open and awaiting a re-submission as well.

**Comment by tinagueth** [comment] 2022-04-27 17:54
@c-suh good to know about #248 and #249. #173 should be closed as the lab.hydrocarbon_spectra was resubmitted #235

**Comment by c-suh** [comment] 2022-04-27 17:57
@tinagueth ah, I missed that. Thank you. So, just this item then.

**Comment by tinagueth** [comment] 2022-04-27 18:06
@c-suh no worries. The validation report is currently running. Should be able to resubmit mars2020_meda tomorrow. Thanks

**Comment by tinagueth** [comment] 2022-05-02 17:59
@c-suh I resubmitted mars2020_meda (#251). Thanks

**Comment by c-suh** [comment] 2022-05-10 16:13
duplicate of #151. Resubmitted in #251 but was already included in #248. Most recently resubmitted in #254.

**Comment by c-suh** [comment] 2022-11-03 15:09
@tinagueth kindly pointed out this package has been archived. Thank you!

**Closed** 2022-11-03 15:08 UTC
Labels: duplicate, nssdca-delivery
