### ISSUE TITLE
Issue #426 add new namespace "nco"

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS/operations#437] opened 2023-09-14 12:40 UTC
Add the namespace "vco" to the Namespace Registry and the config.properties file.

The Venus Climate Orbiter Akatsuki Mission Local Data Dictionary contains classes, attributes and rules specific to the Venus Climate Orbiter Akatsuki Mission and its instruments.

This LDD is needed to describe the specifics of both the Venus Climate Orbiter Akatsuki Mission and the instrumentation on board the Akatsuki spacecraft.

**Comment by c-suh** [comment] 2023-10-04 21:40
Duplicate of https://github.com/NASA-PDS/operations/issues/426; opened by Steve after he added this to the PDS Namespace Registry.

**Closed by c-suh** 2023-10-04 21:40 UTC
Labels: duplicate, sprint-backlog, task, i&t.skip
